account/urls.py
from django.urls import path, include, reverse
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy

app_name = "account"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
    # path('edit/', views.edit, name='edit'),
]

bunin_science_band/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.conf.urls import handler404, handler500
from .sitemaps import NewsSitemap, EventsSitemap, MembersSitemap

sitemaps = {
    "news": NewsSitemap,
    "events": EventsSitemap,
    "members": MembersSitemap,
}

urlpatterns = [
    path("account/", include("account.urls")),
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("news/", include("news.urls", namespace="news")),
    path("members/", include("memebers.urls", namespace="members")),
    path("events/", include("events.urls", namespace="events")),
    path("contacts/", include("info.urls", namespace="contacts")),
    re_path(
        r"^robots\.txt$",
        TemplateView.as_view(
            template_name="robots.txt", content_type="text/plain"
        ),
    ),
    re_path(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

handler404 = "home.views.page_not_found_view"
handler500 = "home.views.server_error_view"

events/urls.py
from django.urls import path
from . import views
from likes.views import event_like

app_name = "events"

urlpatterns = [
    path("", views.events_list, name="events_list"),
    path("tag/<slug:tag_slug>/", views.events_list, name="events_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:events>/",
        views.events_detail,
        name="events_detail",
    ),
    path("<int:events_id>/share/", views.events_share, name="events_share"),
    path("<int:events_id>/comment/", views.events_comment, name="events_comment"),
    path("search/", views.events_search, name="events_search"),
    path(
        "comment/{<int:comment_id>}",
        views.events_comment_delete,
        name="events_comment_delete",
    ),
    path("events_like/{<int:event_id>}", event_like, name="events_like"),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("500/", views.exp_500, name="exp_500"),
]

comments/models.py
from django.db import models
from django.utils.translation import gettext as _
from events.models import Event
from news.models import News


class Comment(models.Model):
    """Модель комментариев для записей."""

    events = models.ForeignKey(
        Event,
        related_name="comments",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="События",
    )
    news = models.ForeignKey(
        News,
        on_delete=models.SET_NULL,
        related_name="comments",
        blank=True,
        null=True,
        verbose_name="Новости",
    )
    name = models.CharField(max_length=80, verbose_name="Имя")
    email = models.EmailField(verbose_name="Email")
    body = models.TextField(verbose_name="Содержимое")
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания"
    )
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Дата и время обновления"
    )
    active = models.BooleanField(default=True, verbose_name="Активен")

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"]),
        ]

    def __str__(self):
        return f"Комментарий от {self.name}:{self.body}"

events/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings
from taggit.managers import TaggableManager
from memebers.models import Member
from viewer.models import Viewer


class PublishedManager(models.Manager):
    """Менеджер для Событий."""

    def get_queryset(self):
        """Возвращает список всех опубликованных Событий."""

        return super().get_queryset().filter(status=Event.Status.PUBLISHED)


class Event(models.Model):
    """Модель событий сообщества."""

    class Status(models.TextChoices):
        """Статус записи на сайте."""

        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    viewes = models.ManyToManyField(
        Viewer,
        related_name="viewes",
        blank=True,
        null=True,
        verbose_name="Просмотры",
    )
    title = models.CharField(max_length=250, verbose_name="Заголовок")
    slug = models.SlugField(
        max_length=250, unique_for_date="publish", verbose_name="Slug"
    )
    members = models.ManyToManyField(
        Member,
        related_name="members",
        blank=True,
        null=True,
        verbose_name="Участники",
        help_text="Участники, которые организуют событие",
    )
    likes = models.ManyToManyField(
        User,
        related_name="event_likes",
        blank=True,
        null=True,
        verbose_name="Лайки",
    )
    body = models.TextField(
        verbose_name="Содержимое", help_text="Введите текст о Событии"
    )
    publish = models.DateTimeField(
        default=timezone.now(), verbose_name="Дата и время публикации"
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания"
    )
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Дата и время обновления"
    )
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name="Статус",
    )
    document = models.FileField(
        upload_to="events/%Y/%m/%d/", blank=True, verbose_name="Документ"
    )

    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]
        verbose_name = _("event")
        verbose_name_plural = _("events")

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse(
            "events:events_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ],
        )

    def total_views(self) -> int:
        """Возвращает количество просмотров на записе."""

        return self.viewes.count()

    def number_of_likes(self) -> int:
        """Возвращает количество лайков на записе."""

        return self.likes.count()


class EventImage(models.Model):
    """Модель изображения, связанного с Событием."""

    event = models.ManyToManyField(
        Event,
        related_name="images",
        blank=True,
        verbose_name="Событие",
        help_text="Событие связанное с картинкой",
    )
    image = models.ImageField(
        upload_to="event/%Y/%m/%d/", blank=True, verbose_name="Изображение"
    )

    class Meta:
        verbose_name = _("event_img")
        verbose_name_plural = _("event_imgs")

    def __str__(self) -> str:
        return self.image

events/forms.py
from django import forms
from comments.models import Comment


class EmailEventForm(forms.Form):
    """Форма для отправки События по email (репост события)."""

    name = forms.CharField(max_length=25, label="Имя")
    to = forms.EmailField(label="Кому (email)")
    comments = forms.CharField(
        required=False, widget=forms.Textarea, label="Комментарий"
    )


class CommentForm(forms.ModelForm):
    """Форма для отправки комментария под записью События."""

    email = forms.EmailField(disabled=True, label="Email")
    name = forms.CharField(disabled=True, label="Имя")

    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    """Форма поиска по событиям."""

    query = forms.CharField(label="Запрос")

events/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.views.decorators.cache import cache_page
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from taggit.models import Tag
from .models import Event
from comments.models import Comment
from .forms import EmailEventForm, CommentForm, SearchForm
from . import services
import viewer.services as viewer_services
import utils.list_helper as list_helper
from utils.core import transaction_safe_view
from .tasks import share_by_email
import logging

logger = logging.getLogger(__name__)


@transaction_safe_view
@login_required(login_url=settings.LOGIN_URL)
def events_comment_delete(
    request: HttpRequest, comment_id: int
) -> HttpResponseRedirect:
    """Вью для удаления комментария."""

    comment = get_object_or_404(Comment, id=comment_id)
    event = comment.events
    logger.warning(
        f"Удалили комментарий {comment.name} : {comment.body} под событием {event.title} - {event.get_absolute_url()}"
    )
    comment.delete()
    return redirect(event)


def events_search(request: HttpRequest) -> HttpResponse:
    """Вью для поиска по Событиям."""

    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            results = services.get_search_result_by_trigram(query, 0.1)
    return render(
        request,
        "events/events/search.html",
        {"form": form, "query": query, "results": results},
    )


@cache_page(1)
@transaction_safe_view
@require_POST
@login_required(login_url=settings.LOGIN_URL)
def events_comment(request: HttpRequest, events_id: int) -> HttpResponse:
    """Вью для комментирования."""
    events = get_object_or_404(
        Event, id=events_id, status=Event.Status.PUBLISHED
    )
    comment = None
    # Комментарий был отправлен
    initial_dict = {"name": request.user.username, "email": request.user.email}
    form = CommentForm(data=request.POST, initial=initial_dict)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.events = events
        comment.news = None
        # Сохранить комментарий в базе данных
        comment.save()
    return render(
        request,
        "events/events/comment.html",
        {"events": events, "form": form, "comment": comment},
    )


@login_required(login_url=settings.LOGIN_URL)
def events_share(request: HttpRequest, events_id: int) -> HttpResponse:
    """Вью чтобы поделиться событием по email."""

    events = get_object_or_404(
        Event, id=events_id, status=Event.Status.PUBLISHED
    )
    sent = False
    if request.method == "POST":
        form = EmailEventForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            events_url = request.build_absolute_uri(events.get_absolute_url())
            sent = share_by_email.delay(
                cd["name"],
                events.title,
                events_url,
                cd["comments"],
                settings.EMAIL_HOST_USER,
                cd["to"],
            )
    else:
        form = EmailEventForm()
    return render(
        request,
        "events/events/share.html",
        {"events": events, "form": form, "sent": sent},
    )


def events_detail(
    request: HttpRequest, year: int, month: int, day: int, events: str
) -> HttpResponse:
    """Вью для отображения детальной информации о Событии."""

    events: Event = get_object_or_404(
        Event,
        status=Event.Status.PUBLISHED,
        slug=events,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    client_ip = viewer_services.get_client_ip(
        request.META.get("HTTP_X_FORWARDED_FOR"),
        request.META.get("REMOTE_ADDR"),
    )
    viewer_services.add_view(events, client_ip)
    # Список активных комментариев к этому посту
    comments = list_helper.get_active_comments(events)
    form = None
    if request.user.is_authenticated:
        form = CommentForm(
            initial={"name": request.user.username, "email": request.user.email}
        )
    events_tags_ids = list_helper.get_resource_tags_ids(events)
    similar_events = services.get_similar_events(events_tags_ids, events.id, 4)
    return render(
        request,
        "events/events/detail.html",
        {
            "events": events,
            "comments": comments,
            "form": form,
            "similar_events": similar_events,
        },
    )


def events_list(request: HttpRequest, tag_slug: str = None) -> HttpResponse:
    """Вью для отображения списка Событий."""

    # x = 1 / 0
    events_list = None
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        events_list = services.get_all_published_events_by_tag(tag)
    else:
        events_list = services.get_all_published_events()
    page_number = request.GET.get("page", 1)
    events = list_helper.get_paginated(events_list, page_number, 3)
    return render(
        request, "events/events/list.html", {"events": events, "tag": tag}
    )

templates/events/events/comment.html
{% extends "base.html" %}

{% block title %}Комментарий{% endblock %}



{% block content %}
  {% if comment %}
    <h2>Ваш комментарий был добавлен</h2>
    <p><a href="{{ events.get_absolute_url }}">Вернуться к Событию</a></p>
  {% else %}
    {% include "events/events/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

templates/events/events/detail.html
{% extends "base.html" %}
{% load events_tags %}
{% load static %}

{% block title %}{{ events.title }}{% endblock %}

{% block content %}


<h1>{{ events.title }}</h1>
<p>Просмотры : {{events.total_views}}</p>
<p class="date">
  Теги: 
  {% for tag in events.tags.all %}
                <a href="{% url "events:events_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %} 
</p>
{% if events.members %}
<p class="date">
  Организаторы:
  {% for member in events.members.all %}
  <a href="{{ member.get_absolute_url }}">{{ member.surname }} {{ member.name }} </a>
  {% endfor %}
</p>
{% endif %}
<p class="date">
  Опубликовано {{ events.publish }} 
</p>


{{ events.body|markdown }}

{% if events.document %}
<div class="download-card">
  <img src="{% static 'img/download-ico.png' %}" alt="Download Icon" class="download-icon">
  <h3 class="download-title">{{ events.document|filename }}</h3>
  <a class="btn btn-main" href="{{ events.document.url }}" download>Скачать</a>
</div>

{% endif %}

{% if events.images %}
{% with events.images.all as event_images %}


<div id="carouselExampleIndicators" class="carousel slide" data-bs-interval="false">
  <div class="carousel-indicators">

    {% for image in event_images %}

    <button type="button" 
    data-bs-target="#carouselExampleIndicators" 
    data-bs-slide-to="{{ forloop.counter }}" 
    class="active" aria-current="true"
    aria-label="Slide {{ forloop.counter }}"></button>

    {% endfor %}

  </div>
  <div class="carousel-inner">
    {% for image in event_images %}
    <div class="carousel-item img-fluid active">
      <img class="w-100 d-block" src="{{ image.image.url }}" alt="{{ events.title }}">
    </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

{% endwith %}
{% endif %}

<div>

<p>
<a class="btn btn-main" href="{% url "events:events_share" events.id %}">
  Поделиться новостью
</a>
</p>

<p>
{% if user.is_authenticated %}

<span id="like" style="font-size:200%;color:#da166c;" data-resource="events" data-event-id="{{ events.id }}" >&hearts;</span>
{% else %}
<a class="btn btn-main" href="{% url 'account:login' %}">Log-in чтобы оценить запись!</a><br>
<span style="font-size:200%;color:#da166c;">&hearts;</span>
{% endif %}
<strong id="like-count" class="text-secondary">{{ events.number_of_likes }} </strong>
</p>

</div>

<div class="detail-news-similar">
<h2 class="detail-news-similar-header">Похожие События</h2>
<ul class="aside-icon">
{% for events in similar_events %}
<li class="latest">
  <a href="{{ events.get_absolute_url }}">{{ events.title }}</a>
</li>
{% empty %}
Нет похожих Событий.
{% endfor %}
</ul>
</div>

{% with comments.count as total_comments %}
  <h2 class="detail-news-comment-header">
    {{ total_comments }} {{ total_comments|ru_plural:"комментарий,комментария, комментариев" }}
  </h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
  <p class="info">
    {{ comment.name }}
    {{ comment.created }}
    {% if request.user.is_superuser %}
  <a href="{% url "events:events_comment_delete"  comment.id %}">X</a>
  {% endif %}
  </p>
  {{ comment.body|linebreaks }}

</div>
{% empty %}
<p>Нет комментариев</p>
{% endfor %}
{% if request.user.is_authenticated %}
{% include "events/events/includes/comment_form.html" %}
{% else %}
<a href="{% url "account:login" %}">Войдите</a> или <a href="{% url "account:register" %}">зарегистрируйтесь</a> чтобы оставлять комментарии.
{% endif %}

{% endblock %}


templates/events/events/latest_events.html
<ul>
    {% for news in latest_news %}
      <li>
        <a href="{{ news.get_absolute_url }}">{{ news.title }}</a>
      </li>
    {% endfor %}
  </ul>

templates/events/events/list.html
{% extends 'base.html' %}
{% load events_tags %}

{% block title %}События{% endblock %}

{% block content %}
    <h1>СОБЫТИЯ</h1>

    <div class="news-search"><a class="btn btn-main" role="button" href="{% url "events:events_search"  %}">Поиск по Событиям</a></div>

    {% if tag %}
    <h2>События с тегом: "{{ tag.name }}"</h2>
{% endif %}

{% for event in events %}
     <!-- START Событие -->

        <div class="card my-2 d-flex">
            <div class="card-body">
              <h2 class="card-title">
                <a href="{{ event.get_absolute_url }}">{{ event.title }}</a>
              </h2>
              <p class="card-text"> {{ event.body|markdown|truncatewords_html:30 }}</p>
              <p class="card-text">
                <small class="text-body-secondary">
                Теги:
                    {% for tag in event.tags.all %}
                    <a href="{% url "events:events_list_by_tag" tag.slug %}">
                        {{ tag.name }}
                      </a>
                      {% if not forloop.last %}, {% endif %}
                    {% endfor %}
              </small>
            </p>
              <p class="card-text">
                <small class="text-body-secondary"> 
                Опубликовано {{ event.publish }} 
              </small>
            </p>

            {% if event.images %}
            {% with event.images.all|first as image%}
            <img class="card-img-top" src="{{ image.image.url }}" alt="{{ event.title }}">
            {% endwith %}
            {% endif %}
            <div class="card-more-info"><a class="btn btn-main" role="button" href="{{ event.get_absolute_url }}">Подробнее</a></div>
          </div>
          </div>


    <!-- END Событие -->
    {% endfor %}
    {% include "../../pagination.html" with page=events %}
{% endblock %}



templates/events/events/search.html
{% extends "base.html" %}
{% load events_tags %}

{% block title %}Поиск{% endblock %}

{% block content %}
  {% if query %}
    <h1>События, содержащие "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
      Найдено результатов {{ total_results }} 
      {{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4>
        <a href="{{ post.get_absolute_url }}">
          {{ post.title }}
        </a>
      </h4>
      {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
      <p>Нет результатов по запросу.</p>
      {% endfor %}
      <p><a href="{% url "events:events_search" %}">Искать снова</a></p>
    {% else %}
      <h1>Поиск по событиям</h1>
      <form method="get">
        {{ form.as_p }}
        <input class="btn btn-main" type="submit" value="Поиск">
      </form>
    {% endif %}
  {% endblock %}

templates/events/events/share.html
{% extends "base.html" %}

{% block title %}Делимся{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail успешно отправлен</h1>
    <p>
      "{{ events.title }}" успешно отправлен {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Поделиться "{{ events.title }}" по e-mail</h1>
    <form method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <input class="btn btn-main" type="submit" value="Поделиться">
    </form>
  {% endif %}
{% endblock %}