bunin_science_band/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.conf.urls import handler404, handler500
from .sitemaps import NewsSitemap, EventsSitemap, MembersSitemap

sitemaps = {
    "news": NewsSitemap,
    "events": EventsSitemap,
    "members": MembersSitemap,
}

urlpatterns = [
    path("account/", include("account.urls")),
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("news/", include("news.urls", namespace="news")),
    path("members/", include("memebers.urls", namespace="members")),
    path("events/", include("events.urls", namespace="events")),
    path("contacts/", include("info.urls", namespace="contacts")),
    re_path(
        r"^robots\.txt$",
        TemplateView.as_view(
            template_name="robots.txt", content_type="text/plain"
        ),
    ),
    re_path(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

handler404 = "home.views.page_not_found_view"
handler500 = "home.views.server_error_view"

events/urls.py
from django.urls import path
from . import views
from likes.views import event_like

app_name = "events"

urlpatterns = [
    path("", views.events_list, name="events_list"),
    path("tag/<slug:tag_slug>/", views.events_list, name="events_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:events>/",
        views.events_detail,
        name="events_detail",
    ),
    path("<int:events_id>/share/", views.events_share, name="events_share"),
    path("<int:events_id>/comment/", views.events_comment, name="events_comment"),
    path("search/", views.events_search, name="events_search"),
    path(
        "comment/{<int:comment_id>}",
        views.events_comment_delete,
        name="events_comment_delete",
    ),
    path("events_like/{<int:event_id>}", event_like, name="events_like"),
]

home/urls.py
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("500/", views.exp_500, name="exp_500"),
]

info/urls.py
from django.urls import path, include
from . import views

app_name = "contacts"

urlpatterns = [
    path("", views.contacts, name="contacts"),
]

memebers/urls.py
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path("", views.members_list, name="members_list"),
    path(
        "tag/<slug:tag_slug>/", views.members_list, name="members_list_by_tag"
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:members>/",
        views.members_detail,
        name="members_detail",
    ),
]

news/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed
from likes.views import news_like

app_name = "news"

urlpatterns = [
    path("", views.news_list, name="news_list"),
    path("tag/<slug:tag_slug>/", views.news_list, name="news_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:news>/",
        views.news_detail,
        name="news_detail",
    ),
    path("<int:news_id>/share/", views.news_share, name="news_share"),
    path("<int:news_id>/comment/", views.news_comment, name="news_comment"),
    path("feed/", LatestPostsFeed(5, 30), name="news_feed"),
    path("search/", views.news_search, name="news_search"),
    path(
        "comment/{<int:comment_id>}",
        views.news_comment_delete,
        name="news_comment_delete",
    ),
    path("news_like/{<int:news_id>}", news_like, name="news_like"),
]

templates/base.html
{% load news_tags %}
{% load static %}
{% load cache %}

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta property="og:image" content="{% static "img/logo.png" %}" />
  <meta property="og:image:width" content="300" />
  <meta property="og:image:height" content="300" />
  <meta name="description" property="og:description" content="Совет молодых учёных ЕГУ">
  <meta name="keywords" content="егу, совет молодых учных, совет молодых учёных егу, егу им. И.А. Бунина">
  <meta name="author" content="PyLounge">
  <title>{% block title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css" rel="stylesheet"/>
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
  <link href="{% static "css/main.css" %}" rel="stylesheet">
</head>
<body>



<div class="container-fluid p-0 sticky-top">
  <div class="row">
    <!-- HEADER -->
    <header class="col-xs-12">
      <nav class="navbar navbar-light navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url "home:index" %}">
            <img src="{%  static 'img/logo.png' %}" alt="" class="nav-logo"
            class="d-inline-block align-text-center"/>
            Совет молодых учёных 
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url "members:members_list" %}">Участники</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "news:news_list" %}">Новости</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "events:events_list" %}">События</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "contacts:contacts" %}">Контакты</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Журнал</a>
              </li>
            </ul>
          </div>
          <span class="nav-isauth">
          {% if request.user.is_authenticated %}
            {{ request.user.first_name|default:request.user.username }},
            <a href="{% url "account:logout" %}">Выйти</a>
          {% else %}
            <a href="{% url "account:login" %}">Войти</a>
          {% endif %}
        </span>
        </div>
      </nav>
    </header>
  </div>
</div>

<div class="container">
  <div class="row">
    <!-- ОСНОВНОЙ КОНТЕНТ -->
    <section class="col-xs-12">
      <div class="row">
        <!-- MAIN -->
        <main class="col-md-8 col-lg-9">
            {% block content %}
            {% endblock %}
        </main>
        <!-- ASIDE -->
        <div class="col-md-4 col-lg-3">
          <div class="row">
            {% cache 30 aside %} 
            <!-- ASIDE #1 -->
            <aside class="col-sm-6 col-md-12">
              <div>
                <h2>Молодые ученые представляют</h2>
                <p>
                Новостей на сайте уже: {% total_news %}
                </p>
                <p>
                  <a href="{% url "news:news_feed" %}"> 
                    Подпишись на наш RSS-фид
                  </a>
                </p>
                <h3>Последние новости</h3>
                {% show_latest_news 3 %}
                <h3>Наиболее обсуждаемые</h3>
                {% get_most_commented_news as most_commented_news %}
                <ul class="aside-icon">
                  {% for news in most_commented_news %}
                  <li class="aside-icon-comment">
                    <a href="{{ news.get_absolute_url }}">{{ news.title }}</a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </aside>
            {% endcache %}
          </div>
        </div>
      </div>
    </section>
  </div>



</div>

<div class="container-fluid p-0">
    <!-- FOOTER -->
    <footer class="col-xs-12">
      © 2023 Елецкий государственный университет. Все права защищены.
      При использовании материалов сайта ссылка обязательна.
      
      Россия, ул. Коммунаров, 28, Елец, Липецкая обл., 399770.
    </footer>
  </div>



  
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/pagination.html
  <nav aria-label="...">
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">Предыдущая</a>
    </li>
  {% endif %}
    <li class="page-item active" aria-current="page">
      <span class="page-link">
         {{ page.number }} из {{ page.paginator.num_pages }}
      </span>
    </li>
    {% if page.has_next %}
    <li class="page-item">
    <a class="page-link" href="?page={{ page.next_page_number }}">Следующая</a>
  </li>
      {% endif %}
  </ul>
</nav>