bunin_science_band/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.conf.urls import handler404, handler500
from .sitemaps import NewsSitemap, EventsSitemap, MembersSitemap

sitemaps = {
    "news": NewsSitemap,
    "events": EventsSitemap,
    "members": MembersSitemap,
}

urlpatterns = [
    path("account/", include("account.urls")),
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("news/", include("news.urls", namespace="news")),
    path("members/", include("memebers.urls", namespace="members")),
    path("events/", include("events.urls", namespace="events")),
    path("contacts/", include("info.urls", namespace="contacts")),
    re_path(
        r"^robots\.txt$",
        TemplateView.as_view(
            template_name="robots.txt", content_type="text/plain"
        ),
    ),
    re_path(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

handler404 = "home.views.page_not_found_view"
handler500 = "home.views.server_error_view"

home/urls.py
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("500/", views.exp_500, name="exp_500"),
]

memebers/urls.py
from django.urls import path
from . import views

app_name = "members"

urlpatterns = [
    path("", views.members_list, name="members_list"),
    path(
        "tag/<slug:tag_slug>/", views.members_list, name="members_list_by_tag"
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:members>/",
        views.members_detail,
        name="members_detail",
    ),
]

templates/members/members/detail.html
{% extends "base.html" %}
{% load members_tags %}

{% block title %}{{ members.surname }}{% endblock %}

{% block content %}

<div class="member-detail">
  <div class="member-detail-main">
  <h1>{{ members.surname }} {{ members.name }} {{ members.midname }}</h1>
  <p class="date">
    Опубликовано {{ members.publish }} 
  </p>
  <p class="tags">
    Теги:
    {% for tag in members.tags.all %}
    <a href="{% url "members:members_list_by_tag" tag.slug %}">
        {{ tag.name }}
      </a>
      {% if not forloop.last %}, {% endif %}
    {% endfor %}
  </p>

  <p>Cфера научных интересов: {{ members.science_fields }} </p>  
  <p>Степень/должность: {{ members.rank }} </p> 

  <div class="member-contact">
      <p><span>Телефон: </span>{{ members.phone }}</p>
      <p>Почта: {{ members.email }}</p>
      <p>Социальные сети: {{ members.socials }}</p>
  </div>

<div class="member-profile-photo-detail">
    {% if members.image %}
    <img src="{{ members.image.url }}" alt="{{ members.surname }}"/>
    {% endif %}
</div>

</div>

<div class="member-desc">Сведения: {{ members.description |markdown }}</div>

</div>


  



<h2>Похожие участники</h2>
{% for member in similar_members %}
  <p>
    <a href="{{ member.get_absolute_url }}">{{ member.surname }}</a>
  </p>
  {% empty %}
  Нет похожих участников.
{% endfor %}
{% endblock %}

templates/members/members/list.html
{% extends 'base.html' %}
{% load members_tags %}

{% block title %}Участники сообщества{% endblock %}

{% block content %}
    <h1>УЧАСТНИКИ СООБЩЕСТВА</h1>
    {% if tag %}
        <h2>Участники с научными интересами: "{{ tag.name }}"</h2>
    {% endif %}
    {% for member in members %}
    <div class="member">
    <div class="member-info">
    <h2>
        <a href="{{ member.get_absolute_url }}">
        {{ member.surname }} {{ member.name }}  {{ member.midname  }}
        </a>
    </h2>
    <p class="tags">
        Теги:
        {% for tag in member.tags.all %}
        <a href="{% url "members:members_list_by_tag" tag.slug %}">
            {{ tag.name }}
          </a>
          {% if not forloop.last %}, {% endif %}
        {% endfor %}
      </p>
    <p>Cфера научных интересов: {{ member.science_fields }} </p>  
    <p>Степень/должность: {{ member.rank }} </p> 
    Сведения: {{ member.description |markdown|truncatewords_html:30 }}
    <div class="member-contact">
        <p><span>Телефон: </span>{{ member.phone }}</p>
        <p>Почта: {{ member.email }}</p>
        <p>Социальные сети: {{ member.socials }}</p>
    </div>
</div>
<div class="member-profile-photo">
    {% if member.image %}
    <img src="{{ member.image.url }}" alt="{{ member.surname }}">
    {% endif %}
</div>
</div>
    {% endfor %}
    {% include "../../pagination.html" with page=members %}
{% endblock %}