account/urls.py
from django.urls import path, include, reverse
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy

app_name = "account"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
    # path('edit/', views.edit, name='edit'),
]

bunin_science_band/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.conf.urls import handler404, handler500
from .sitemaps import NewsSitemap, EventsSitemap, MembersSitemap

sitemaps = {
    "news": NewsSitemap,
    "events": EventsSitemap,
    "members": MembersSitemap,
}

urlpatterns = [
    path("account/", include("account.urls")),
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("news/", include("news.urls", namespace="news")),
    path("members/", include("memebers.urls", namespace="members")),
    path("events/", include("events.urls", namespace="events")),
    path("contacts/", include("info.urls", namespace="contacts")),
    re_path(
        r"^robots\.txt$",
        TemplateView.as_view(
            template_name="robots.txt", content_type="text/plain"
        ),
    ),
    re_path(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

handler404 = "home.views.page_not_found_view"
handler500 = "home.views.server_error_view"

home/urls.py
from django.urls import path, include
from . import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
    path("500/", views.exp_500, name="exp_500"),
]

news/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed
from likes.views import news_like

app_name = "news"

urlpatterns = [
    path("", views.news_list, name="news_list"),
    path("tag/<slug:tag_slug>/", views.news_list, name="news_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:news>/",
        views.news_detail,
        name="news_detail",
    ),
    path("<int:news_id>/share/", views.news_share, name="news_share"),
    path("<int:news_id>/comment/", views.news_comment, name="news_comment"),
    path("feed/", LatestPostsFeed(5, 30), name="news_feed"),
    path("search/", views.news_search, name="news_search"),
    path(
        "comment/{<int:comment_id>}",
        views.news_comment_delete,
        name="news_comment_delete",
    ),
    path("news_like/{<int:news_id>}", news_like, name="news_like"),
]

comments/models.py
from django.db import models
from django.utils.translation import gettext as _
from events.models import Event
from news.models import News


class Comment(models.Model):
    """Модель комментариев для записей."""

    events = models.ForeignKey(
        Event,
        related_name="comments",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="События",
    )
    news = models.ForeignKey(
        News,
        on_delete=models.SET_NULL,
        related_name="comments",
        blank=True,
        null=True,
        verbose_name="Новости",
    )
    name = models.CharField(max_length=80, verbose_name="Имя")
    email = models.EmailField(verbose_name="Email")
    body = models.TextField(verbose_name="Содержимое")
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания"
    )
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Дата и время обновления"
    )
    active = models.BooleanField(default=True, verbose_name="Активен")

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"]),
        ]

    def __str__(self):
        return f"Комментарий от {self.name}:{self.body}"

news/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings
from taggit.managers import TaggableManager
from viewer.models import Viewer


class PublishedManager(models.Manager):
    """Менеджер для Новостей."""

    def get_queryset(self):
        """Возвращает список всех опубликованных Новостей."""

        return super().get_queryset().filter(status=News.Status.PUBLISHED)


class News(models.Model):
    """Модель новостей сообщества."""

    class Status(models.TextChoices):
        """Статус записи на сайте."""

        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    viewes = models.ManyToManyField(
        Viewer,
        related_name="views",
        blank=True,
        null=True,
        verbose_name="Просмотры",
    )
    likes = models.ManyToManyField(
        User,
        related_name="news_likes",
        blank=True,
        null=True,
        verbose_name="Лайки",
    )
    title = models.CharField(max_length=250, verbose_name="Заголовок")
    slug = models.SlugField(
        max_length=250, unique_for_date="publish", verbose_name="Слаг"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="news_news",
        verbose_name="Автор",
    )
    body = models.TextField(verbose_name="Содержание")
    publish = models.DateTimeField(
        default=timezone.now(), verbose_name="Дата и время публикации"
    )
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания"
    )
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Дата и время обновления"
    )
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name="Статус",
    )

    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]
        verbose_name = _("news")
        verbose_name_plural = _("news")

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse(
            "news:news_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ],
        )

    def total_views(self) -> int:
        """Возвращает количество просмотров на новосте."""

        return self.viewes.count()

    def number_of_likes(self) -> int:
        """Возвращает количество лайков на записе."""

        return self.likes.count()


class NewsImage(models.Model):
    """Модель изображения, связанного с Новостью."""

    news = models.ManyToManyField(
        News, related_name="images", blank=True, verbose_name="Новость"
    )
    image = models.ImageField(
        upload_to="users/%Y/%m/%d/", blank=True, verbose_name="Изображение"
    )

    def __str__(self) -> str:
        return self.image

news/forms.py
from django import forms
from comments.models import Comment


class EmailNewsForm(forms.Form):
    """Форма для отправки Новости по email (репост новости)."""

    name = forms.CharField(max_length=25, label="Имя")
    to = forms.EmailField(label="Кому")
    comments = forms.CharField(
        required=False, widget=forms.Textarea, label="Комментарий"
    )


class CommentForm(forms.ModelForm):
    """Форма для отправки комментария под записью Новостью."""

    email = forms.EmailField(disabled=True, label="Email")
    name = forms.CharField(disabled=True, label="Имя")

    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchForm(forms.Form):
    """Форма поиска по Новостям."""

    query = forms.CharField(label="Запрос")

news/views.py
import logging
import viewer.services as viewer_services
import utils.list_helper as list_helper
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.shortcuts import redirect
from django.views.decorators.cache import cache_page
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from taggit.models import Tag
from . import services
from .models import News
from .forms import EmailNewsForm, CommentForm, SearchForm
from .tasks import share_by_email
from comments.models import Comment
from viewer.models import Viewer
from utils.core import transaction_safe_view


logger = logging.getLogger(__name__)


def news_search(request: HttpRequest) -> HttpResponse:
    """Вью для поиска по Новостям."""

    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data["query"]
            results = services.get_search_result_by_trigram(query, 0.1)
    return render(
        request,
        "news/news/search.html",
        {"form": form, "query": query, "results": results},
    )


@cache_page(1)
@transaction_safe_view
@require_POST
@login_required
def news_comment(request: HttpRequest, news_id: int) -> HttpResponse:
    """Вью для комментирования."""

    news = get_object_or_404(News, id=news_id, status=News.Status.PUBLISHED)
    comment = None
    # Комментарий был отправлен
    initial_dict = {"name": request.user.username, "email": request.user.email}
    form = CommentForm(data=request.POST, initial=initial_dict)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.news = news
        comment.events = None
        # Сохранить комментарий в базе данных
        comment.save()
    return render(
        request,
        "news/news/comment.html",
        {"news": news, "form": form, "comment": comment},
    )


@cache_page(1)
@transaction_safe_view
@login_required
def news_comment_delete(
    request: HttpRequest, comment_id: int
) -> HttpResponseRedirect:
    """Вью для удаления комментария."""

    comment = get_object_or_404(Comment, id=comment_id)
    news = comment.news
    logger.warning(
        f"Удалили комментарий {comment.name} : {comment.body} под новостью {news.title} - {news.get_absolute_url()}"
    )
    comment.delete()
    return redirect(news)


@login_required(login_url=settings.LOGIN_URL)
def news_share(request: HttpRequest, news_id: int) -> HttpResponse:
    """Вью чтобы поделиться новостью по email."""

    news = get_object_or_404(News, id=news_id, status=News.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailNewsForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            news_url = request.build_absolute_uri(news.get_absolute_url())
            sent = share_by_email.delay(
                cd["name"],
                news.title,
                news_url,
                cd["comments"],
                settings.EMAIL_HOST_USER,
                cd["to"],
            )
    else:
        form = EmailNewsForm()
    return render(
        request,
        "news/news/share.html",
        {"news": news, "form": form, "sent": sent},
    )


def news_detail(
    request: HttpRequest, year: int, month: int, day: int, news: str
) -> HttpResponse:
    """Вью для отображения детальной информации о Новости."""

    news = get_object_or_404(
        News,
        status=News.Status.PUBLISHED,
        slug=news,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    # Список активных комментариев к этому посту
    client_ip = viewer_services.get_client_ip(
        request.META.get("HTTP_X_FORWARDED_FOR"),
        request.META.get("REMOTE_ADDR"),
    )
    viewer_services.add_view(news, client_ip)
    comments = list_helper.get_active_comments(news)
    form = None
    # Форма для комментирования пользователями
    if request.user.is_authenticated:
        form = CommentForm(
            initial={"name": request.user.username, "email": request.user.email}
        )
    news_tags_ids = list_helper.get_resource_tags_ids(news)
    similar_news = services.get_similar_news(news_tags_ids, news.id, 3)
    print(similar_news)
    return render(
        request,
        "news/news/detail.html",
        {
            "news": news,
            "comments": comments,
            "form": form,
            "similar_news": similar_news,
        },
    )


def news_list(request: HttpRequest, tag_slug: str = None) -> HttpResponse:
    """Вью для отображения списка Событий."""

    news_list = None
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        news_list = services.get_all_published_news_by_tag(tag)
    else:
        news_list = services.get_all_published_news()
    page_number = request.GET.get("page", 1)
    news = list_helper.get_paginated(news_list, page_number, 3)
    return render(request, "news/news/list.html", {"news": news, "tag": tag})

templates/news/news/comment.html
{% extends "base.html" %}

{% block title %}Добавить комментарий{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Ваш комментарий был добавлен.</h2>
    <p><a href="{{ news.get_absolute_url }}">Вернуться к новости</a></p>
  {% else %}
    {% include "news/news/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

templates/news/news/detail.html
{% extends "base.html" %}
{% load news_tags %}

{% block title %}{{ news.title }}{% endblock %}

{% block content %}
  <h1>{{ news.title }}</h1>
  <p>Просмотры : {{news.total_views}}</p>
  <p class="date">
    Опубликовано {{ news.publish }} пользователем {{ news.author }}
  </p>
  {{ news.body|markdown }}
  {% if news.images %}
    {% for image in news.images.all %}
    <img class="detail" src="{{ image.image.url }}" alt="{{ news.title }}">
    {% endfor %}
    {% endif %}

<div>

<p>
  <a class="btn btn-main" href="{% url "news:news_share" news.id %}">
    Поделиться новостью
  </a>
</p>

<p>
{% if user.is_authenticated %}
<!--<a href="{% url 'news:news_like' news.id %}" style="font-size:200%;color:#da166c;" >&hearts;</a>-->
<span id="like" style="font-size:200%;color:#da166c;" data-resource="news" data-event-id="{{ news.id }}" >&hearts;</span>
{% else %}
<a class="btn btn-main" href="{% url 'account:login' %}">Log in чтобы оценить запись !</a><br>
<span style="font-size:200%;color:#da166c;">&hearts;</span>
{% endif %}
<strong id="like-count" class="text-secondary">{{ news.number_of_likes }} </strong>
</p>

</div>

<div class="detail-news-similar">
<h2 class="detail-news-similar-header">Похожие новости</h2>
<ul class="aside-icon">
{% for news in similar_news %}
  <li class="latest">
    <a href="{{ news.get_absolute_url }}">{{ news.title }}</a>
  </li>
  {% empty %}
  Нет похожих новостей.
{% endfor %}
</ul>
</div>

  {% with comments.count as total_comments %}
    <h2 class="detail-news-comment-header">
      {{ total_comments }} {{ total_comments|ru_plural:"комментарий,комментария, комментариев" }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
  <div class="comment">
    <p class="info">
      {{ comment.name }}
      {{ comment.created }}
      {% if request.user.is_superuser %}
    <a href="{% url "news:news_comment_delete"  comment.id %}">X</a>
    {% endif %}
    </p>
    {{ comment.body|linebreaks }}

  </div>
{% empty %}
  <p>Нет комментариев</p>
{% endfor %}
{% if request.user.is_authenticated %}
{% include "news/news/includes/comment_form.html" %}
{% else %}
<a href="{% url "account:login" %}">Войдите</a> или <a href="{% url "account:register" %}">зарегистрируйтесь</a> чтобы оставлять комментарии.
{% endif %}
{% endblock %}

templates/news/news/latest_news.html
<ul class="aside-icon">
    {% for news in latest_news %}
      <li class="latest">
        <a href="{{ news.get_absolute_url }}">{{ news.title }}</a>
      </li>
    {% endfor %}
  </ul>

templates/news/news/list.html
{% extends 'base.html' %}
{% load news_tags %}

{% block title %}Новости{% endblock %}
{% block content %}
    <h1>НОВОСТИ</h1>
    <div class="news-search"><a class="btn btn-main" role="button" href="{% url "news:news_search"  %}">Поиск по новостям</a></div>

    {% if tag %}
        <h2>Новости с тегом: "{{ tag.name }}"</h2>
    {% endif %}

    {% for ns in news %}
     <!-- START Новость -->

        <div class="card my-2 d-flex">
            <div class="card-body">
              <h2 class="card-title">
                <a href="{{ ns.get_absolute_url }}">{{ ns.title }}</a>
              </h2>
              <p class="card-text"> {{ ns.body|markdown|truncatewords_html:30 }}</p>
              <p class="card-text">
                <small class="text-body-secondary">
                Tags:
                {% for tag in ns.tags.all %}
                <a href="{% url "news:news_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
              </small>
            </p>
              <p class="card-text">
                <small class="text-body-secondary"> 
                Published {{ ns.publish }} by {{ ns.author }}
              </small>
            </p>

            {% if ns.images %}
            {% with ns.images.all|first as image%}
            <img class="card-img-top" src="{{ image.image.url }}" alt="{{ ns.title }}">
            {% endwith %}
            {% endif %}
            <div class="card-more-info"><a class="btn btn-main" role="button" href="{{ ns.get_absolute_url }}">Подробнее</a></div>
          </div>
          </div>
    <!-- END Новость -->
    {% endfor %}


    {% include "../../pagination.html" with page=news %}
{% endblock %}

templates/news/news/search.html
{% extends "base.html" %}
{% load news_tags %}

{% block title %}Поиск по Новостям{% endblock %}

{% block content %}
  {% if query %}
    <h1>Новости, содержащие запрос: "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Найдено результатов {{ total_results }} 
        {{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4>
        <a href="{{ post.get_absolute_url }}">
          {{ post.title }}
        </a>
      </h4>
      {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
      <p>Не найдено результатов по данному запросу</p>
      {% endfor %}
      <p><a href="{% url "news:news_search" %}">Искать снова</a></p>
    {% else %}
      <h1>Поиск по новостям</h1>
      <form method="get">
        {{ form.as_p }}
        <input class="btn-main" type="submit" value="Поиск">
      </form>
    {% endif %}
  {% endblock %}

templates/news/news/share.html
{% extends "base.html" %}

{% block title %}Делимся{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail успешно отправлен</h1>
    <p>
      "{{ news.title }}" успешно отправлен {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Поделиться "{{ news.title }}" по e-mail</h1>
    <form method="POST">
      {{ form.as_p }}
      {% csrf_token %}
      <input class="btn btn-main" type="submit" value="Поделиться">
    </form>
  {% endif %}
{% endblock %}